[package]
name = "component-init"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
wasm-encoder = "0.29.0"
wasm-convert = { git = "https://github.com/dicej/wasm-convert" }
async-trait = "0.1.68"
futures = "0.3.28"
wasmparser = "0.107.0"
